# Generated by Django 4.0.2 on 2022-05-23 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_FreshProducts', '0003_alter_magazzino_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto_vendita',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='punto_vendita',
            name='Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App_FreshProducts.licenze'),
        ),
    ]
