# Generated by Django 4.0.2 on 2022-05-23 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_FreshProducts', '0004_punto_vendita_user_alter_punto_vendita_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazzino',
            name='Scadenza',
            field=models.DateTimeField(default=None, verbose_name='Scadenza'),
        ),
        migrations.AlterField(
            model_name='punto_vendita',
            name='Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_FreshProducts.licenze'),
        ),
        migrations.AlterField(
            model_name='punto_vendita',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
