# Generated by Django 4.0.2 on 2022-05-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_FreshProducts', '0013_alter_licenze_data_scadenza_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credenziali',
        ),
    ]
