# Generated by Django 4.0.2 on 2022-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_FreshProducts', '0014_delete_credenziali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenze',
            name='Code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='Barcode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
